---
title: "daily_indices"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)
library(lubridate)
library(forcats)

```


Input: `nldas_hourly_index_rod`
Key output: `daily_indices_rod` (temp, hi, wbgt at daily mean, max, min, 0600-local [24])



Load hourly index dataframe 

```{r}

hourly_nldas <-
  read_rds(file = "data/nldas_hourly_index_rod.rds")

hourly_nldas %>% 
  summary()

hourly_nldas %>% 
  count(site_name) %>% as.data.frame()


daily_indices_rod <-
  read_rds(file = "data/daily_indices_rod")

```



# Daily indices

```{r}

# mean, max, min
daily_indices_rod1 <-
  hourly_nldas  %>%
      dplyr::select(-utc_dttm) %>% 
      group_by(site_name, date = lubridate::date(local_dttm)) %>%
      dplyr::summarise_at(
            .vars = vars(tmp_f, hi_f, wbgt_f, tmp_c, hi_c, wbgt_c),
            .funs = c(mean = "mean", max = "max", min = "min"))

# local daily 0600 indices

daily_indices_rod2 <-
  hourly_nldas  %>%
      dplyr::select(-utc_dttm) %>% 
      group_by(site_name, date = lubridate::date(local_dttm)) %>%
      dplyr::filter(lubridate::hour(local_dttm) == 6) %>% 
      rename_with(.fn = ~paste0(., "_0600"), .cols = c("tmp_f", "hi_f", "wbgt_f", "tmp_c", "hi_c", "wbgt_c")) %>% 
  dplyr::select(-local_dttm)
      
  

daily_indices_rod <-
   daily_indices_rod1 %>% 
    left_join(daily_indices_rod2, by = c("site_name", "date"))
    
  
# write_rds(daily_indices_rod, "data/daily_indices_rod") # 262,992 rows x 26 columns



```


## Inspect hourly indices

```{r}
hourly_nldas %>% 
  dplyr::filter(lubridate::year(local_dttm) %in% 1998:2019) %>%
  summary()

hourly_nldas %>% 
  dplyr::filter(lubridate::year(local_dttm) %in% 1998:2019) %>%
    group_by(site_name) %>% 
    summarise_at(c("tmp_f", "hi_f", "wbgt_f"), mean) %>%
    arrange(desc(tmp_f)) %>% 
    as.data.frame()
```

## Inspect daily indices

```{r}

daily_indices_rod %>% 
  dplyr::filter(lubridate::year(date) %in% 1998:2019) %>%
  summary()



daily_indices_rod %>% 
  dplyr::filter(lubridate::year(date) %in% 1998:2019,
                lubridate::month(date) %in% 8) %>%
    group_by(site_name) %>% 
    summarise_at(c("tmp_f_mean", "hi_f_mean", "wbgt_f_mean", "tmp_f_max", "hi_f_max", "wbgt_f_max"), mean) %>%
    arrange(desc(tmp_f_mean)) %>% 
    as.data.frame()




```


## Camp Pendleton check
!! Temperatures and WBGT appear flipped

```{r, eval = FALSE}

daily_indices_rod %>%
  filter(site_name %in% "MCB Camp Pendleton",
         lubridate::year(date) %in% 2018:2019) %>%
  dplyr::select(site_name, date, tmp_f_mean, tmp_f_max) %>% 
  pivot_longer(c(-site_name, -date), names_to = "index", values_to = "value") %>% 
  ggplot(aes(x = date, y = value, color = index)) +
  geom_point() +
  geom_line(aes(group = date))
  

daily_indices_rod %>%
  filter(site_name %in% "MCB Camp Pendleton",
         lubridate::year(date) %in% 2018:2019) %>%
  dplyr::select(site_name, date, wbgt_f_mean, wbgt_f_max) %>% 
  pivot_longer(c(-site_name, -date), names_to = "index", values_to = "value") %>% 
  ggplot(aes(x = date, y = value, color = index)) +
   geom_point() +
  geom_line(aes(group = date))
    

```

